version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file:
      - .env
    stdin_open: true

networks:
  default:
    external: true
    name: notification-network
